FROM golang:alpine

WORKDIR /usr/src/api

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/api .

EXPOSE 5000

CMD ["api"]